### ISSUE TITLE
Upstreaming

### ISSUE THREAD

**Issue by Leon-Plickat** [Koboldthegreat/river-tag-overlay#1]
Showing the pop-up on output focus change is a nice feature. If you clean your changes up a bit I will consider upstreaming them.

**Comment by smnbl** [comment]
I cleaned it up a bit (the whole retab was a mess 😅). I'm not that familiar with writing wayland applications, I've been using this extensively for the last month and it seems to hold up :) , but an expert opinion would be appreciated.

**Comment by Leon-Plickat** [comment]
[I modified it a bit to fit style and convention](https://git.sr.ht/~leon_plickat/river-tag-overlay/commit/7e2bdefefc2435bcd10617ec55e662fbbfb5f681), but your patch is now part of upstream.

Thanks for the contribution!
